---
title: "Chain Ladder"
output: pdf_document
---

```{r setup, include=FALSE}
library(ChainLadder)
```

Load and Prepare Data

```{r load data}
data(AutoBI)
data <- AutoBI$AutoBIReportedCounts

# Set row and column names
start_year <- 1988
rownames(data) <- seq(start_year, length.out = nrow(data))
colnames(data) <- seq_len(ncol(data))

data
```

Plot Reported Counts Triangle

```{r plot-orignal}
plot(data, main = "Reported Counts Triangle")
```

ChainLadder Projection

```{r ChainLadder-model}
CL <- chainladder(data)
CL$Models
```

Development Factors

```{r dev-factors}
link_factors <- sapply(CL$Models , function(m) coef(m)["x"])
link_factors
```

Predict Full Triangle and Plot

```{r predict-and-plot}
full_triangle <- predict(CL)
full_triangle

plot(full_triangle, main = "Completed Reported Counts Triangle")
plot(full_triangle, lattice = TRUE)
```

Reserve Calculation

```{r reserves}
ultimates <- rowSums(full_triangle)
reported_to_date <- rowSums(data, na.rm = TRUE)
reserves <- ultimates - reported_to_date

summary_df <- data.frame(
  AccidentYear = rownames(data),
  Reported = reported_to_date,
  Ultimate = ultimates,
  Reserves = reserves
)
summary_df
```
